server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-service
          uri: https://github.com/caitoVilas/university-config
          search-paths: config-data
application:
  name: config-service